cask_args appdir: '/Applications'
tap 'homebrew/cask'
tap 'caskroom/versions'
cask 'spectacle'
cask 'iterm2'
cask 'sublime-text'
cask 'caffeine'
cask 'postico'
cask 'alfred'
cask 'intellij-idea-ce'
cask '1password'
cask 'firefox'